import { NestFactory } from '@nestjs/core';
import { ValidationPipe } from '@nestjs/common';
import { AppModule } from './app.module';
import { SwaggerModule, DocumentBuilder } from '@nestjs/swagger';
import * as dotenv from 'dotenv';
import { Announcement } from './announcements/announcements.schema';
import { Creator } from './creators/creators.schema';
import { Announcer } from './announcers/announcers.schema';
import { Click } from './clicks/clicks.schema';
import { Reference } from './references/references.schema';
import { NestExpressApplication } from '@nestjs/platform-express';
import { resolve } from 'path';
import { writeFileSync } from 'fs';

async function bootstrap() {
  const cors = require('cors');
  const serverUrl = 'https://mac-backend-six.vercel.app';
  const app: NestExpressApplication = await NestFactory.create(AppModule);
  const config = new DocumentBuilder()
    .setTitle('MAC API')
    .setDescription('APIs for MAC application.')
    .setVersion('1.0')
    .addTag('mac')
    .build();

  const document = SwaggerModule.createDocument(app, config, {
    extraModels: [Announcement, Creator, Announcer, Click, Reference],
  });
  SwaggerModule.setup('swagger', app, document);
  // WORKAROUND:
  // We serve the "static" folder (generated by "ncc") behind the "/swagger" URL so that all Swagger UI assets get fetched properly
  // app.useStaticAssets(join(__dirname, '/static'), {
  //   prefix: '/swagger',
  // });

  app.use(cors());
  dotenv.config();
  app.useGlobalPipes(new ValidationPipe());
  await app.listen(3000);
  // get the swagger json file (if app is running in development mode)
  // get the swagger json file (if app is running in development mode)
  if (process.env.NODE_ENV === 'development') {
    const pathToSwaggerStaticFolder = resolve(process.cwd(), 'swagger-static');

    // write swagger json file
    const pathToSwaggerJson = resolve(
      pathToSwaggerStaticFolder,
      'swagger.json',
    );
    const swaggerJson = JSON.stringify(document, null, 2);
    writeFileSync(pathToSwaggerJson, swaggerJson);
    console.log(`Swagger JSON file written to: '/swagger-static/swagger.json'`);
  }
}

bootstrap();
