import { NestFactory } from '@nestjs/core';
import { ValidationPipe } from '@nestjs/common';
import { AppModule } from './app.module';
import { SwaggerModule, DocumentBuilder } from '@nestjs/swagger';
import * as dotenv from 'dotenv';
import { Announcement } from './announcements/announcements.schema';
import { Creator } from './creators/creators.schema';
import { Announcer } from './announcers/announcers.schema';
import { Click } from './clicks/clicks.schema';
import { Reference } from './references/references.schema';
import { NestExpressApplication } from '@nestjs/platform-express';
import { resolve } from 'path';
import { writeFileSync, createWriteStream } from 'fs';
import { get } from 'http';

async function bootstrap() {
  const cors = require('cors');
  const serverUrl = 'https://mac-backend-six.vercel.app';
  const app = await NestFactory.create(AppModule);
  const config = new DocumentBuilder()
    .setTitle('MAC API')
    .setDescription('APIs for MAC application.')
    .setVersion('1.0')
    .addTag('mac')
    .build();

  const document = SwaggerModule.createDocument(app, config, {
    extraModels: [Announcement, Creator, Announcer, Click, Reference],
  });
  SwaggerModule.setup('swagger', app, document);
  // WORKAROUND:
  // We serve the "static" folder (generated by "ncc") behind the "/swagger" URL so that all Swagger UI assets get fetched properly
  // app.useStaticAssets(join(__dirname, '/static'), {
  //   prefix: '/swagger',
  // });

  app.use(cors());
  dotenv.config();
  app.useGlobalPipes(new ValidationPipe());
  await app.listen(3000);
  // get the swagger json file (if app is running in development mode)
  if (process.env.NODE_ENV === 'development') {
    // write swagger ui files
    get(`${serverUrl}/swagger/swagger-ui-bundle.js`, function (response) {
      response.pipe(createWriteStream('swagger-static/swagger-ui-bundle.js'));
      console.log(
        `Swagger UI bundle file written to: '/swagger-static/swagger-ui-bundle.js'`,
      );
    });

    get(`${serverUrl}/swagger/swagger-ui-init.js`, function (response) {
      response.pipe(createWriteStream('swagger-static/swagger-ui-init.js'));
      console.log(
        `Swagger UI init file written to: '/swagger-static/swagger-ui-init.js'`,
      );
    });

    get(
      `${serverUrl}/swagger/swagger-ui-standalone-preset.js`,
      function (response) {
        response.pipe(
          createWriteStream('swagger-static/swagger-ui-standalone-preset.js'),
        );
        console.log(
          `Swagger UI standalone preset file written to: '/swagger-static/swagger-ui-standalone-preset.js'`,
        );
      },
    );

    get(`${serverUrl}/swagger/swagger-ui.css`, function (response) {
      response.pipe(createWriteStream('swagger-static/swagger-ui.css'));
      console.log(
        `Swagger UI css file written to: '/swagger-static/swagger-ui.css'`,
      );
    });
  }
}

bootstrap();
